title: Zixuan Wang
description: Personal website of Zixuan Wang.
remote_theme: just-the-docs/just-the-docs
url: https://wang-zixuan.github.io

plugins:
 - jekyll-remote-theme
 - jekyll-seo-tag
 - rake

defaults:
  - scope: {path: "docs/"}
    values: {layout: default}

search_enabled: false

aux_links:
  "LinkedIn": 
    - "https://www.linkedin.com/in/chloe-zxwang/"
  "GitHub":
    - "https://github.com/wang-zixuan"

nav:
  include_posts: true
